/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 ./public/Overview.gltf -T 
Files: ./public/Overview.gltf [3.55MB] > Overview-transformed.glb [3.69MB] (-4%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Overview-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.mesh_1.geometry} material={materials.PaletteMaterial002} />
    </group>
  )
}

useGLTF.preload('/Overview-transformed.glb')
