/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/Sheeesh.gltf -T 
Files: ./public/Sheeesh.gltf [915.39KB] > Sheeesh-transformed.glb [5.67MB] (-519%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Sheeesh-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.mesh_1.geometry} material={materials.PaletteMaterial002} />
    </group>
  )
}

useGLTF.preload('/Sheeesh-transformed.glb')
