/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/Themaninthearena.gltf -T 
Files: ./public/Themaninthearena.gltf [3.59MB] > Themaninthearena-transformed.glb [5.77MB] (-61%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Themaninthearena-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body2.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes['ap_triumph_spitfire_(9)'].geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Body1.geometry} material={nodes.Body1.material} />
      <mesh geometry={nodes['92865A595_Medium-Strength_Grade_5_Steel_Hex_Head_Screw'].geometry} material={nodes['92865A595_Medium-Strength_Grade_5_Steel_Hex_Head_Screw'].material} />
      <mesh geometry={nodes['Â³Â¹cznik'].geometry} material={nodes['Â³Â¹cznik'].material} />
    </group>
  )
}

useGLTF.preload('/Themaninthearena-transformed.glb')
